import type { ArticleData } from "./Article";

export const guideReconciliation: ArticleData = {
  slug: "guide/gst-reconciliation",
  title: "Complete Guide to GST Reconciliation (2026) | TechBharat Studios",
  description: "Step-by-step guide to GST reconciliation in India: what it is, why it matters for ITC, and how to reconcile GSTR-2B with your books quickly.",
  h1: "Complete Guide to GST Reconciliation",
  intro: "GST reconciliation is the monthly process of matching the purchase invoices in your books (Tally or Purchase Register) against GSTR-2B issued by the GST portal. Correct reconciliation protects your Input Tax Credit (ITC), reduces notices, and keeps GSTR-3B filing clean.",
  sections: [
    {
      h2: "What is GST reconciliation?",
      body: [
        "GST reconciliation compares two invoice-level data sets: the purchases you have recorded in your accounting software, and the inward supplies your suppliers have reported through GSTR-1, which appear in your GSTR-2B.",
        "Any invoice that does not appear in GSTR-2B blocks ITC for that month. Any invoice in GSTR-2B that is missing from your books may indicate an unrecorded purchase. Both gaps need attention before filing GSTR-3B.",
      ],
    },
    {
      h2: "Why monthly reconciliation matters",
      body: [
        "From the 2022 ITC reforms, ITC is allowed strictly on the basis of GSTR-2B. If a supplier delays filing GSTR-1, that invoice will not appear in your 2B and you cannot claim ITC for it that month.",
        "Reconciling every month lets you follow up with suppliers early, claim ITC in the correct period, and avoid interest, penalties and 2A/2B mismatch notices.",
      ],
    },
    {
      h2: "Steps to reconcile GSTR-2B with Tally",
      body: [
        "1. Export the purchase register from Tally for the relevant month in Excel.",
        "2. Download GSTR-2B JSON or Excel from the GST portal for the same return period.",
        "3. Upload both files into a reconciliation tool that matches by GSTIN and invoice number.",
        "4. Review matched, missing-in-books and missing-in-2B invoices, plus mismatches in taxable value or tax.",
        "5. Correct entries, follow up with suppliers for missing invoices, and finalise ITC before filing GSTR-3B.",
      ],
    },
    {
      h2: "Manual vs automated reconciliation",
      body: [
        "Manual VLOOKUPs in Excel work for very small data sets but break down at scale: column names differ, invoice numbers carry prefixes, dates are stored as text, and GSTINs may contain typos.",
        "An automated tool auto-detects columns, normalises invoice numbers, flags GSTIN typos and surfaces 'possible matches' so you do not lose ITC on minor data entry differences.",
      ],
    },
  ],
};

export const guideVsTally: ArticleData = {
  slug: "guide/gstr-2b-vs-tally",
  title: "GSTR-2B vs Tally: How to Match Invoices Correctly",
  description: "How GSTR-2B differs from Tally purchase data, common mismatch reasons (invoice number prefixes, dates, GSTIN typos), and how to match them accurately.",
  h1: "GSTR-2B vs Tally: How to Match Invoices",
  intro: "GSTR-2B is generated by the GST portal from the GSTR-1 your suppliers file. Tally holds whatever your team has entered. The two rarely agree on the first try — here is how to compare them correctly and resolve mismatches.",
  sections: [
    {
      h2: "Key differences between GSTR-2B and Tally data",
      body: [
        "GSTR-2B is supplier-reported and locked once generated on the 14th of each month. Tally is buyer-recorded and editable any time.",
        "GSTR-2B uses the invoice number exactly as the supplier filed it. Tally may store the same invoice with a series prefix, leading zeros, or a different format.",
        "Taxable value in Tally may include or exclude rounding and freight, while GSTR-2B uses the value the supplier declared.",
      ],
    },
    {
      h2: "Most common reasons invoices do not match",
      body: [
        "Invoice number formatting: 'INV-001/24-25' vs '001'. Smart matching strips prefixes and zero padding.",
        "GSTIN typos: a single wrong character makes the system treat two records as different suppliers.",
        "Date mismatches: supplier dated 31-Mar, you booked 02-Apr — falls into a different return period.",
        "Tax slab differences: a 12% vs 18% disagreement usually means HSN was reported differently.",
      ],
    },
    {
      h2: "Recommended matching logic",
      body: [
        "Match primarily on GSTIN + normalised invoice number. Use taxable value and tax amounts as tie-breakers.",
        "Treat near matches (>90% invoice number similarity, same GSTIN, same tax amount) as 'possible matches' for review rather than discarding them.",
        "Flag GSTINs that appear in only one of the two files as potential typos for manual review.",
      ],
    },
  ],
};

export const guideFaq: ArticleData = {
  slug: "guide/faq",
  title: "GST Reconciliation FAQ — Common Questions Answered",
  description: "Answers to common questions about GSTR-2B reconciliation, ITC claims, file formats, data privacy, and using the free TechBharat reconciliation tool.",
  h1: "GST Reconciliation FAQ",
  intro: "Quick answers to the questions accountants and business owners ask most often about GSTR-2B reconciliation and our free tool.",
  sections: [],
  faq: [
    { q: "What is GSTR-2B?", a: "GSTR-2B is an auto-generated, static ITC statement issued by the GST portal on the 14th of every month. It lists invoices reported by your suppliers in their GSTR-1 and is the basis for claiming Input Tax Credit." },
    { q: "How often should I reconcile?", a: "Reconcile every month before filing GSTR-3B. Waiting until quarter-end or year-end makes follow-ups with suppliers much harder and risks losing ITC in the correct period." },
    { q: "Can I reconcile without uploading my data to a server?", a: "Yes. Our tool runs entirely in your browser. Your Excel files are never uploaded — all parsing and matching happens locally on your device." },
    { q: "Does the tool work with Tally Prime exports?", a: "Yes. It accepts standard Tally exports as well as custom Purchase Register Excel files. Column auto-detection handles different layouts." },
    { q: "What file formats are supported?", a: "Excel files in .xlsx and .xls formats. Download GSTR-2B as Excel from the GST portal and export Tally data as Excel." },
    { q: "Is the tool really free?", a: "Yes — you get free exports after a one-time sign-up. Uploading files and previewing reconciliation results does not require an account at all." },
    { q: "Will it detect GSTIN typos?", a: "Yes. The tool highlights GSTINs that appear on only one side as potential typos and offers 'possible match' suggestions for review." },
  ],
};

export const guideTroubleshooting: ArticleData = {
  slug: "guide/troubleshooting",
  title: "Troubleshooting GST Reconciliation Mismatches",
  description: "Fix common GSTR-2B reconciliation issues: missing invoices, GSTIN typos, invoice number format mismatches, tax differences and column detection problems.",
  h1: "Troubleshooting Reconciliation Mismatches",
  intro: "Most reconciliation problems fall into a few well-known patterns. This guide walks through each one and the practical fix.",
  sections: [
    {
      h2: "Invoice missing from GSTR-2B",
      body: [
        "Cause: the supplier has not yet filed GSTR-1 for that period, or filed it after the 11th cut-off.",
        "Fix: contact the supplier, ask them to include the invoice in the next return, and claim ITC in the month it appears in your 2B.",
      ],
    },
    {
      h2: "Invoice in 2B but not in your books",
      body: [
        "Cause: the supplier reported it but your team has not booked the purchase yet, or booked it under a different vendor ledger.",
        "Fix: locate the original invoice, book it in the correct period, and re-run reconciliation.",
      ],
    },
    {
      h2: "Invoice number does not match",
      body: [
        "Cause: prefixes, leading zeros, slashes or financial-year suffixes formatted differently.",
        "Fix: use a tool with normalised matching that strips common prefixes and compares the numeric core. Treat near matches as 'possible matches' and review.",
      ],
    },
    {
      h2: "Taxable value or tax amount differs",
      body: [
        "Cause: rounding differences, freight or discount handled differently, or wrong HSN/tax slab on one side.",
        "Fix: compare invoice copy with both records. Pass an accounting adjustment if you were wrong; ask the supplier to amend GSTR-1 if they were wrong.",
      ],
    },
    {
      h2: "Tool says it cannot detect columns",
      body: [
        "Cause: header row is not on the first row, headers are merged cells, or non-standard column names are used.",
        "Fix: open the Excel file, ensure the header row is the first row of data, unmerge cells and rename columns to standard terms like GSTIN, Invoice No, Invoice Date, Taxable Value, IGST, CGST, SGST.",
      ],
    },
  ],
};

export const allArticles = [guideReconciliation, guideVsTally, guideFaq, guideTroubleshooting];
